# Homework 3
Data source: http://archive.ics.uci.edu/ml/datasets/Polish+companies+bankruptcy+data

In [1]:
from scipy.io import arff
import pandas as pd
import numpy as np

In [2]:
data = arff.loadarff('4year.arff')
df = pd.DataFrame(data[0])

In [3]:
df['bankruptcy'] = (df['class']==b'1')
del df['class']
df.columns = ['X{0:02d}'.format(k) for k in range(1,65)] + ['bankruptcy']

In [4]:
df.describe()

X01          X02          X03           X04           X05  \
count  9791.000000  9791.000000  9791.000000   9749.000000  9.771000e+03   
mean      0.043019     0.596404     0.130959      8.136600  6.465164e+01   
std       0.359321     4.587122     4.559074    290.647281  1.475939e+04   
min     -12.458000     0.000000  -445.910000     -0.045319 -3.794600e+05   
25%       0.001321     0.263145     0.020377      1.047000 -5.121700e+01   
50%       0.041364     0.467740     0.199290      1.591800 -5.557600e-02   
75%       0.111130     0.689255     0.410670      2.880400  5.573200e+01   
max      20.482000   446.910000    22.769000  27146.000000  1.034100e+06   

               X06          X07           X08          X09          X10  ...  \
count  9791.000000  9791.000000   9773.000000  9792.000000  9791.000000  ...   
mean     -0.059273     0.059446     19.884016     1.882296     0.389040  ...   
std       6.812754     0.533344    698.697015    17.674650     4.590299  ...   
min    -486.820000   -12.458000     -1.848200    -0.032371  -445.910000  ...   
25%      -0.000578     0.003004      0.428300     1.006675     0.294440  ...   
50%       0.000000     0.048820      1.088700     1.161300     0.510450  ...   
75%       0.065322     0.126940      2.691000     1.970225     0.714290  ...   
max     322.200000    38.618000  53209.000000  1704.800000    12.602000  ...   

                X55          X56          X57          X58          X59  \
count  9.792000e+03  9771.000000  9791.000000  9776.000000  9791.000000   
mean   7.686330e+03    -0.992263     0.035022     1.133287     0.856053   
std    7.605261e+04    77.007971     8.945365     8.038201    26.393305   
min   -7.132200e+05 -7522.100000  -597.420000   -30.892000  -284.380000   
25%    2.184000e+01     0.003121     0.008768     0.885722     0.000000   
50%    9.503300e+02     0.043679     0.098026     0.958305     0.002129   
75%    4.694550e+03     0.117170     0.242680     0.996163     0.211790   
max    6.123700e+06   112.020000   226.760000   668.750000  1661.000000   

                 X60            X61           X62          X63           X64  
count    9178.000000    9760.000000  9.771000e+03  9749.000000   9561.000000  
mean      118.156064      25.194430  2.015157e+03     8.660813     35.949619  
std      3230.316692    1099.260821  1.171461e+05    60.838202    483.318623  
min         0.000000     -12.656000 -1.496500e+04    -0.024390     -0.000015  
25%         5.356325       4.267700  4.323400e+01     2.938800      2.012900  
50%         9.482000       6.283550  7.472900e+01     4.848900      4.041600  
75%        19.506000       9.938200  1.233450e+02     8.363800      9.413500  
max    251570.000000  108000.000000  1.077900e+07  5662.400000  21153.000000  

[8 rows x 64 columns]

In [5]:
sum(df.bankruptcy == True)

515

In [6]:
from sklearn.impute import SimpleImputer
imp_mean = SimpleImputer(missing_values=np.nan, strategy='mean')
X_imp = imp_mean.fit_transform(df.values)

In [7]:
from sklearn.model_selection import train_test_split

X, y = X_imp[:, :-1], X_imp[:, -1]

X_train, X_test, y_train, y_test =\
    train_test_split(X, y, 
                     test_size=0.3, 
                     random_state=0, 
                     stratify=y)

In [8]:
from sklearn.preprocessing import StandardScaler

stdsc = StandardScaler()
X_train_std = stdsc.fit_transform(X_train)
X_test_std = stdsc.transform(X_test)

## Extract 3 features
using PAC method

In [9]:
from sklearn.decomposition import PCA

pca = PCA()
X_train_pca_all = pca.fit_transform(X_train_std)
ratio_W = pca.explained_variance_ratio_
ratio_W

array([1.74965147e-01, 9.12170614e-02, 8.11462753e-02, 6.60978536e-02,
       5.34907000e-02, 4.77403147e-02, 4.52512866e-02, 3.75944904e-02,
       3.09870220e-02, 2.73574041e-02, 2.47781178e-02, 2.37694259e-02,
       2.14071017e-02, 1.93912479e-02, 1.87274814e-02, 1.77110790e-02,
       1.65536886e-02, 1.57051058e-02, 1.56659171e-02, 1.56226617e-02,
       1.55940372e-02, 1.50542306e-02, 1.46645375e-02, 1.37159896e-02,
       1.24855836e-02, 1.19136769e-02, 1.04292709e-02, 1.00335104e-02,
       8.14754016e-03, 7.35890007e-03, 6.54681467e-03, 6.00453134e-03,
       5.15662266e-03, 3.14637614e-03, 2.85083437e-03, 2.37100553e-03,
       1.89838710e-03, 1.66717684e-03, 1.06146851e-03, 9.48607140e-04,
       8.35276042e-04, 5.76474830e-04, 4.32129697e-04, 4.10481782e-04,
       4.05670927e-04, 3.50842516e-04, 3.04907775e-04, 1.60963047e-04,
       1.05934786e-04, 7.59569331e-05, 4.19319942e-05, 2.93811469e-05,
       2.14767430e-05, 7.44698613e-06, 4.95202807e-06, 4.73370690e-06,
      

In [10]:
ratio_W[[0,1,2]]
#The projection matrix of the three most important features

array([0.17496515, 0.09121706, 0.08114628])

In [11]:
#By set n_components = 3, we can directly get the data transform result with 3 features
pca = PCA(n_components=3)
X_train_pca = pca.fit_transform(X_train_std)
pca.explained_variance_ratio_

array([0.17496515, 0.09121706, 0.08114628])

## Apply LR / SVM / Decision Tree
Using the selected features from PCA method above

In [12]:
#transform test data with features above
X_test_pca = X_test_std * ratio_W
X_test_pca = X_test_pca[:,[0,1,2]]
X_test_pca

array([[-0.01684046,  0.23018804, -0.29101752],
       [ 0.08281446, -0.02577176,  0.04627296],
       [ 0.01083527, -0.01482487, -0.01920844],
       ...,
       [-0.00349956, -0.01173213, -0.01073525],
       [-0.0136628 , -0.01907937, -0.01478147],
       [-0.04634374, -0.00811868,  0.02765729]])

In [13]:
# LR
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr = lr.fit(X_train_pca, y_train)

print('Training accuracy:', lr.score(X_train_pca, y_train))
print('Test accuracy:', lr.score(X_test_pca, y_test))

Training accuracy: 0.946892325649256
Test accuracy: 0.9472430224642614


C:\Users\NiYee\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [14]:
# SVM 
from sklearn.svm import SVC

svm = SVC(kernel='linear', random_state=1, C=1.0)
svm.fit(X_train_pca, y_train)

print('Training accuracy:', svm.score(X_train_pca, y_train))
print('Test accuracy:', svm.score(X_test_pca, y_test))

Training accuracy: 0.9474759264662971
Test accuracy: 0.9472430224642614


In [15]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier

tree = DecisionTreeClassifier(criterion='gini', 
                              max_depth=6, 
                              random_state=1)
tree.fit(X_train_pca, y_train)

print('Training accuracy:', tree.score(X_train_pca, y_train))
print('Test accuracy:', tree.score(X_test_pca, y_test))

Training accuracy: 0.9506857309600233
Test accuracy: 0.9465622872702518


## Implement the methods using pipeline

In [16]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline

pipe_lr = make_pipeline(StandardScaler(),
                        PCA(n_components=3),
                        LogisticRegression(random_state=1))

pipe_lr.fit(X_train, y_train)
y_pred = pipe_lr.predict(X_test)
print('Test Accuracy: %.3f' % pipe_lr.score(X_test, y_test))

Test Accuracy: 0.946


C:\Users\NiYee\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [17]:
pipe_svm = make_pipeline(StandardScaler(),
                        PCA(n_components=3),
                        SVC(kernel='linear', random_state=1, C=1.0))

pipe_svm.fit(X_train, y_train)
y_pred = pipe_svm.predict(X_test)
print('Test Accuracy: %.3f' % pipe_svm.score(X_test, y_test))

Test Accuracy: 0.947


In [18]:
pipe_tree = make_pipeline(StandardScaler(),
                        PCA(n_components=3),
                        DecisionTreeClassifier(criterion='gini', 
                              max_depth=6, 
                              random_state=1))

pipe_tree.fit(X_train, y_train)
y_pred = pipe_tree.predict(X_test)
print('Test Accuracy: %.3f' % pipe_tree.score(X_test, y_test))

Test Accuracy: 0.946


## Use grid search for finding optimal hyperparameters

In [38]:
from sklearn.model_selection import GridSearchCV

pipe_lr = make_pipeline(StandardScaler(),
                        LogisticRegression(random_state=1))

In [39]:
param_grid = {'logisticregression__C': [0.0001, 0.001, 0.01, 0.1, 1, 10.0, 100.0, 1000.0],
              'logisticregression__penalty':['l1','l2']}

gs = GridSearchCV(estimator=pipe_lr, 
                  param_grid=param_grid, 
                  scoring='accuracy', 
                  cv=10,
                  n_jobs=-1)

gs = gs.fit(X_train, y_train)
print(gs.best_score_)
print(gs.best_params_)

0.9474759264662971
{'logisticregression__C': 0.0001, 'logisticregression__penalty': 'l1'}


C:\Users\NiYee\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
